### ISSUE TITLE
I don't know how to setting

### ISSUE THREAD

**Issue by wlccgp3** [lgeiger/hydrogen-launcher#12]
How to launch jupyter consoles connected to Hydrogen inside PlatformIO IDE Terminal?
Can you show me of your setting?

**Comment by lgeiger** [comment]
You don't need to change the settings. Just make sure you have [PlatformIO IDE Terminal](https://github.com/platformio/platformio-atom-ide-terminal) installed:

![platformio](https://cloud.githubusercontent.com/assets/13285808/21818082/bffff466-d766-11e6-8dac-a7940b8b486d.gif)
