### ISSUE TITLE
How exactly does one install hydrogen-launcher?

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [lgeiger/hydrogen-launcher#13]
Sorry if this is trivial. I'm relatively new to Atom, and couldn't find this package when I search for it in settings in Atom. Does it come with Hydrogen already? if not, how should we install it?

**Comment by lgeiger** [comment]
@amelio-vazquez-reina I just added a install section to the docs: https://github.com/lgeiger/hydrogen-launcher#installation

Please ask more questions if you need help.
