### ISSUE TITLE
qtconsole launch doesn't work?

### ISSUE THREAD

**Issue by dhhagan** [lgeiger/hydrogen-launcher#16]
I am trying to force hydrogen-launcher to launch a qtconsole rather than console through the PlatformIO Terminal and edited the settings to force `qtconsole` rather than `console` in the Jupyter Console section. However (even after a restart of Atom), it still launches an ordinary console. 

Is there something I'm missing, or is it behaving incorrectly?

The reason I want to use qtconsole is so (hopefully) I can utilize the qt backend for plots rather than having them embedded or having them pop out with some weird backend (right now, they just show up in preview on macOS). Hopefully I'm doing this right..

**Comment by lgeiger** [comment]
> However (even after a restart of Atom), it still launches an ordinary console.

By "ordinary" do you mean the PlatformIO terminal?

**Comment by dhhagan** [comment]
Yes. It launches in the PlatformIO terminal, but is a `console`, rather than a `qtconsole`. Is that the expected behaviour?

**Comment by lgeiger** [comment]
Are you sure you use the command "Hydrogen Launcher: Launch Jupyter Console" (`cmd-alt-j`)  rather than "Hydrogen Launcher: Launch Jupyter Console in PlatformIO Terminal" (`cmd-alt-shift-j`)?

**Comment by dhhagan** [comment]
Ahh, I was not. So the qtconsole can't be opened in the PlatformIO Terminal then?

**Comment by lgeiger** [comment]
Oh I think I see your problem now.

AFAIK it isn't possible to have a embedded qtconsole inside the PlatformIO Terminal, but I think we should be able to at least spawn it from there.

**Comment by lgeiger** [comment]
Just released `v1.2.1` with a fix.
