### ISSUE TITLE
"Run all" for remote kernels

### ISSUE THREAD

**Issue by bluehope** [lgeiger/hydrogen-launcher#18]
When I try to do (Run all, Run all above), only the local kernels are listed.
It would be good to support remote kernels for (Run all, Run all above).

**Comment by lgeiger** [comment]
If no kernel is running or connected, every "Run" command defaults to starting a new local kernel. This makes it easy to get started.

If you wan't to use remote kernels run "Hydrogen: Connect to Remote Kernel" as described [here](https://nteract.gitbooks.io/hydrogen/docs/Usage/RemoteKernelConnection.html).

After that you can use both "Run all" and "Run all above".
