### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by MeetQingLiu** [lgeiger/hydrogen-launcher#19]
Hello,
When I try to launch any launcher, I got the following Error:
     `the filename, directory name, or volume label syntax is incorrect`

Any ways to solve this problems?

**Comment by lgeiger** [comment]
Could you give more information about your operating system and the full error output?

**Comment by MeetQingLiu** [comment]
![image](https://cloud.githubusercontent.com/assets/28502195/26526779/5238ef6a-43b7-11e7-949f-48bcb0c9563e.png)
In Windows OS
Thank you !

**Comment by lgeiger** [comment]
This looks a error from jupyter itself.

Does running `jupyter console` work?

If not, can you try `conda install jupyter`?

**Comment by MeetQingLiu** [comment]
Yes, It's the erro from jupyter. I reinstall jupyter and it's working now.
Thanks

**Comment by lgeiger** [comment]
Excellent!
