### ISSUE TITLE
Not working with "Cmder" terminal on windows

### ISSUE THREAD

**Issue by Aaronmacaron** [lgeiger/hydrogen-launcher#2]
If i set "cmder" (a quite popular cmd alternative on windows) as the terminal application i get this error message: 

![screenshot](http://img5.fotos-hochladen.net/uploads/unbenanntk6ous07h3x.png)

Looks like it's passing some weird parameters to cmder.

**Comment by lgeiger** [comment]
Thanks for trying it out!

Does it work with the default default terminal (`cmd.exe`)?

I'm not working with windows but I can test it with Cmder next week.

**Comment by Aaronmacaron** [comment]
Yes, with cmd it's working perfectly fine.
I tested it with another terminal called "powershell". It prints following error message and then closes immediately:  
![test](https://cloud.githubusercontent.com/assets/13036008/19525484/607c0e20-9621-11e6-89d3-89489d628473.PNG)

**Comment by lgeiger** [comment]
Thanks a lot for investigating. I'm not a windows user so any feedback is really appreciated.

That error message helps a lot. It looks like the `/k` option is only available for `cmd.exe`. I have to figure out how to support different terminals on windows.

If you are interested in helping [this is the line](https://github.com/nteract/term-launcher/blob/master/index.js#L67) we have to change.

**Comment by felixholub** [comment]
I'm still seeing the error from the first post. So has this been solved and I'm doing something wrong?

**Comment by Aaronmacaron** [comment]
This isn't a problem with hydrogen-launcher but with the dependency <https://github.com/nteract/term-launcher> . I fixed the problem in <https://github.com/nteract/term-launcher/pull/18> . If this gets merged we must update the version of term-launcher to make use of the fix.

**Comment by Aaronmacaron** [comment]
@lgeiger the dependency to term-launcher should be updated to v0.4.0
