### ISSUE TITLE
"Could not find jupyter or ipython."

### ISSUE THREAD

**Issue by dmcnamee** [lgeiger/hydrogen-launcher#23]
...when trying to launch a jupyter console (with or without PlatformIO terminal). Hydrogen runs fine. This occurs for any python script. Any thoughts?

**Comment by dmcnamee** [comment]
brew pip installation of jupyter placed jupyter/ipython commands in /usr/local/share/python/ which was not on the $PATH (though somehow Hydrogen had found it).

(Thanks for putting together this package btw)

**Comment by voronoi** [comment]
hi @dmcnamee I have this same issue, how exactly did you resolve it ?

**Comment by simonsouv** [comment]
hi @dmcnamee, I'd also be interested to know how you resolved this.

I have a python script that I can execute through hydrogen but I cannot launch a terminal with the same error message

Thanks in advance

**Comment by JavierLopatin** [comment]
Same here. Python run smoothly, but Hydrogen Launcher gives a 'Could not find jupyter or ipython' error.
Cheers

**Comment by Dahaniel** [comment]
same here
