### ISSUE TITLE
Crash on Windows when username has a space

### ISSUE THREAD

**Issue by ysaidani** [lgeiger/hydrogen-launcher#32]
When trying to start the launcher (in an external terminal, or a Platformio terminal) on a Windows system where the username contains a space, a command like the following is executed:

`jupyter console --existing C:\Users\User Name\AppData\Roaming\jupyter\runtime\kernel-13f12759-8581-405d-a8b2-2207ba9fdac7.json`

This results in an error, as `C:\Users\User` does not exist and is not the path to a kernel.

I was able to fix this simply by adding a pair of quotation marks around the file path, which I did by changing line 158 in `hydrogen-launcher\node_modules\term-launcher\index.js` (which is part of the definition of the function `getConnectionCommand`):

- Old: ``var args = ` ${jupyterConsole} --existing ${connectionFile}`;``
- New: ``var args = ` ${jupyterConsole} --existing \"${connectionFile}\"`;``

For some reason, the `node_modules\term-launcher\` folder does not exist in the online repository, else I would have changed it myself and made a pull request.

**Comment by wadethestealth** [comment]
Instead of using quotes in some random file you could use `%20` in place of spaces. Also term-launcher is a node_module, which means it is downloaded on install and is not owned by hydrogen-launcher. Thats why you can't find it here.
