### ISSUE TITLE
Launch Terminal fails if directory contains a space

### ISSUE THREAD

**Issue by dnowacki-usgs** [lgeiger/hydrogen-launcher#4]
OS X 10.10.5, Atom 1.11.2, hydrogen-launcher 1.0.2

`Hydrogen Launcher: Launch Terminal` gives an error if your project directory contains a space:

`Command failed: open -a Terminal.app /Users/dnowacki/Documents/Space Dir/py The files /Users/dnowacki/Documents/Space and /Dir/py do not exist.`

(Needs enclosing quotes around full path)

`Hydrogen Launcher: Launch Jupyter Console` works OK with a space, however (and is the real reason I paid the price of admission 👍 )

**Comment by lgeiger** [comment]
Thanks for reporting. I'll fix it when I'm back at home.

**Comment by lgeiger** [comment]
I just released `v1.0.3`. It should work now.

Please report if anything is broken.

**Comment by dnowacki-usgs** [comment]
Awesome, thanks
