### ISSUE TITLE
Doesn't support hydrogen 1.0+

### ISSUE THREAD

**Issue by Trollgeir** [lgeiger/hydrogen-launcher#7]
Jupyter currently doesn't launch since the newer versions of Hydrogen.

**Comment by lgeiger** [comment]
Thanks for noticing. It looks like I forgot to make a release.
I'll ship once I'm at my PC :+1:

**Comment by lgeiger** [comment]
Hydrogen-Launcher v1.1.0 is now published and should work 🚀
