### ISSUE TITLE
[Feature request] platformio-ide-terminal integration

### ISSUE THREAD

**Issue by Trollgeir** [lgeiger/hydrogen-launcher#9]
It would be great if the launcher would integrate with the platformio-ide-terminal (terminal-plus is broken at the moment). Right now I start a terminal and connect manually, but it would be neat to have this functionality automated. Image below shows my UI with this feature.

![alt text](http://i.imgur.com/nFFuzRx.png)

**Comment by lgeiger** [comment]
I haven't used platformio-ide-terminal, but I see it has the possibility to [execute commands from other packages](https://github.com/platformio/platformio-atom-ide-terminal/blob/master/package.json#L46) so this is possible.

**Comment by lgeiger** [comment]
@Trollgeir Thanks for the great idea. I just published `v1.2.0` which integrates with platformio-ide-terminal.
